### ISSUE TITLE
The CI services should utilize the `ci` and `it` profiles

### ISSUE THREAD

**Issue by maxhbr** [eclipse/antenna#179]
### Summary of the Feature
We have the `antenna-testing/antenna-sw360-integration-testing/` and `antenna-testing/antenna-system-test/` which can be activated via the profiles `it` and `ci`. These tests are currently neither activated on travis nor on Jenkins. 

### Acceptance Criteria
- [x] the system test is used or removed
- [x] the integration test is used or removed

### Definition of Done
- [x] Acceptance criteria fulfilled
- [x] A PR is created, the CI infrastructure reports green
- [x] The PR is reviewed and approved
- [x] No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- [x] Test cases are created to prove the functionality of the feature
- [x] Documentation is updated

**Comment by maxhbr** [comment]
The `it` profile corresponds to the integration test written by @greimela-si, which boots up and provisions a SW360 instance, to test the REST integration. It still depends on the SQL dump, which can not be published.

**Comment by maxhbr** [comment]
correspondig PR: https://github.com/eclipse/antenna/pull/195

**Comment by maxhbr** [comment]
The `ci` profile was outdated and did not contain any testcases, which are not already contained in some other tests.

**Comment by blaumeiser-at-bosch** [comment]
Review: 2019-06-27
