### ISSUE TITLE
Java9 travis tests currently always fail with 10min timeout

### ISSUE THREAD

**Issue by maxhbr** [eclipse/antenna#201]
### Summary of the Bug
see e.g. 
- https://travis-ci.org/eclipse/antenna/jobs/550295410

### Acceptance Criteria
- [ ] travis tests no longer fail

### Definition of Done
- [ ] Acceptance criteria fulfilled
- [ ] A test case is created to reproduce the bug
- [ ] A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- [ ] The PR is reviewed and approved
- [ ] No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- [ ] Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Close this, since we do not run Java 9 tests anymore
