### ISSUE TITLE
Investigate possibilities to use ORT Dependency analyzer as analyzer for SW360.antenna

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#22]
The Open Source Review Toolkit provides some scanners for different buildsystems.
https://github.com/heremaps/oss-review-toolkit

we should check whether we can write a generic analyzer that uses their scanner and puts the data to the SW360.antenna workflow.

Here offered us to help implementing this.

**Comment by Martin-Idel-SI** [comment]
ORT Analyzer will soon be ready in Antenna.

PRs connected to this issue:
#51 Add ort analyzer.

At the moment, it cannot be used in the workflow.xml.
