### ISSUE TITLE
Path cannot be resolved correctly when using AntennaGradlePlugin

### ISSUE THREAD

**Issue by volsus83** [eclipse/antenna#240]
### Summary of the Bug
In our setup we want to provide Antenna configuration file in build directory which leads to incorrect paths.

### Steps to reproduce
- antenna configuration is copied to "build/antenna/pom.xml"
- in this config we want to use Maven variables like "project.build.directory" which is not resolved correctly: 
value of entry `<entry key="scan.patterns" value="${project.build.directory}/antenna/dependencies/*"/>`
is resolved to `.../build/antenna/build/antenna/dependencies/*`

### Definition of Done
- [ ] Acceptance criteria fulfilled
- [ ] A test case is created to reproduce the bug
- [ ] A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- [ ] The PR is reviewed and approved
- [ ] No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- [ ] Documentation is updated

**Comment by bs-ondem** [comment]
Hi @volsus83,

thank you for the issue. I was able to reproduce the bug. I will try to include the fix in the release today.

Br,
bs-ondem

**Comment by volsus83** [comment]
Hi @bs-ondem,

great, thank you very much :+1: 

Best regards

**Comment by bs-ondem** [comment]
Fixed with #226

**Comment by blaumeiser-at-bosch** [comment]
Review: 2019-10-02
