### ISSUE TITLE
Sw360  Credentilas in Debug output

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#350]
### Summary of the Bug
When running Antenna with the SW360 Updater in the workflow on debug mode, the credentials are visible in the log output:
```
[DEBUG] HTTP POST http://localhost:8880/authorization/oauth/token
[DEBUG] Accept=[text/plain, application/xml, text/xml, application/json, application/*+xml, application/*+json, */*]
[DEBUG] Writing [grant_type=password&username=admin@sw360.org&password=12345] as "application/x-www-form-urlencoded"
[DEBUG] Response 200 OK
```

### Steps to reproduce
- Activate SW360 in the workflow of the example project
- run it with `mvn package --debug` 
- see credentials in the authentication requests

### Acceptance Criteria
- [ ] Credentials should be replaced with asterisks

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by bs-ondem** [comment]
@neubs-bsi 
I could not reproduce this with the example project. I build the example-project with `mvn clean package --debug` and the debug output looks like:
```
[INFO] Run org.eclipse.sw360.antenna.sw360.workflow.generators.SW360Updater
[DEBUG] License [Apache-2.0] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [ISC] found in SW360.
[DEBUG] License [Apache-2.0] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [htmlArea-1.0] unknown in SW360.
[DEBUG] License [Apache-2.0] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [PropL] unknown in SW360.
[DEBUG] License [BSD-3-Clause] found in SW360.
[DEBUG] License [Apache-2.0] found in SW360.
[DEBUG] License [Apache-2.0] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [ISC] found in SW360.
[DEBUG] License [MIT] found in SW360.
[DEBUG] License [CC-BY-SA-3.0] found in SW360.
```

But i was able to reproduce it with Antenna-1.0.0-RC6. So this was solved somehow after RC6 and this issue can be closed. 
Output with 1.0.0-RC6:
```
[INFO] Let org.eclipse.sw360.antenna.sw360.workflow.generators.SW360Updater generate output
[DEBUG] HTTP POST http://localhost:8080/authorization/oauth/token
[DEBUG] Accept=[text/plain, application/xml, text/xml, application/json, application/*+xml, application/*+json, */*]
[DEBUG] Writing [grant_type=password&username=admin@sw360.org&password=12345] as "application/x-www-form-urlencoded"
[DEBUG] Response 200 OK
[DEBUG] Reading to [java.lang.String] as "application/json;charset=UTF-8"

```

**Comment by blaumeiser-at-bosch** [comment]
Closed due to previous comment
