### ISSUE TITLE
SW360 Release SourceFile is never set and not included in patchRelease

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#353]
### Summary of the Bug
Currently source files could not be uploaded to SW360 as attachement, since the Sw360Release.sourceFile is never set when creating the release from the artifact. 

Furthermore, attachments are only set when first creating a release, not when patched. 

### Steps to reproduce
- Run example project with only the `CSVAnalyzer` active
- `MavenArtifactResolver` downloads source and sets `ArtifactSourceFile` 
- When creating the release from the artifact in `SW360ReleaseAdapterUtils.convertToRelease()` the sourceFile is never set,
- When later checking the condition if (sources should be uploaded and the file exists), obviously it is false and never executed.

### Acceptance Criteria
- [x] Sources File is set
- [x] Attachements are also set when patching a release (will be necessary for compliance tools as well)

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-01-23
