### ISSUE TITLE
SW360 throws RuntimeException for duplicate attachment making Antenna Fail 

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#357]
### Summary of the Bug
When running the same artifact with a source file twice when uploading sources to SW360 a 500 Internal Server Error is thrown. 

##### The reason:
When storing an attachment of the release, SW360 checks if this would be a duplicate attachment to the release in the updating release function. 
https://github.com/eclipse/sw360/blob/9a2098920c7a53f0b187447bbcc747e44ac98601/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java#L707   
If it is, it throws a `RunTimeException` in the `addAttachmentToRelease()` function, causing the error. 

### Steps to reproduce
- run the example project with the SW360 Updater activated and "uploading sources" activated, twice
- Should fail with a 500 null internal server error exception

### Acceptance Criteria
- [x] check for duplicates before calling add Attachments in PatchRelease
- [x] introduce a deserilazation for attachments in releases (currently not handled)
- [x] no 500 Error is thrown

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by neubs-bsi** [comment]
Note: 
We can check for matching filenames. 
But the `sha1` field of an attachment that gets checked as well in the duplicate condition is created and filled within SW360. 
Hence, it is difficult (not possible ?) to pre-test in Antenna before sending the request.

**Comment by neubs-bsi** [comment]
Should be done after #358

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-01-23
