### ISSUE TITLE
Container Deployment for Antenna

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#365]
### Summary of the Improvement
Support a simple deployment as a docker container that can be easily integrated into a CI toolchain.

### Acceptance Criteria
- [ ] A Docker Container can be created that contains an configurable Antenna deployment (e.g. also proprietary additions of Antenna)
- [x] The container can be executed and gets access to a locally checkout project and runs the configured antenna execution in this environment
- [x] The antenna configuration is taken from the local project that is mapped into the container

### Definition of Done
- Acceptance criteria fulfilled
- The ticket describes what has been done and describes how the results can be verified (e.g. new Jenkins step is inserted, the report can be viewed at X)
- All known limitations are listed and it is described how they will be addressed (e.g., a ticket for the remaining stuff)
- Documentation is updated
- The result has been reviewed: Everything works as described and can be verified reading only the documentation

**Comment by neubs-bsi** [comment]
A container can be created too which an Antenna configuration can be mounted. 
Not supported: Proprietary additions of Antenna.
