### ISSUE TITLE
SW360Releases false serialization of MainLicenseId

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#374]
### Summary of the Bug
When tryinig to write the mainLicenseIDs the href of the license is only the ID and not a full href. Even if the mainLicenseIDs have been set manually in SW360 the false href is kept after the mergewith function (surprising, since it should actually be overwritten with release with precedence which is the one from SW360) 
Correct serialization from SW360: 
![image](https://user-images.githubusercontent.com/44478897/70436401-7bea0f00-1a89-11ea-8f46-860ee2a9b75f.png)
False serialization with only ID:
![image](https://user-images.githubusercontent.com/44478897/70436435-93c19300-1a89-11ea-8ead-9118b51ec3d0.png)

One reason is that there is `!=null `check for the licenses that can only ever be an empty hashset and when setting the mainLicenseIds the href is not set, but the short name, leading to loss of information. 

### Steps to reproduce
1.
- Add the Apache-2.0 License manually to a SW360 instance
- Let the example project run
- no mainLicense Information is set
2. 
- set mainLicenseId manually for a component
- go debugging in the merge with function
- see that wrong href is kept

### Acceptance Criteria
- [x] main License Ids is serialized correctly with an href 
- [x] main License Ids is set correctly in merge function

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-01-23
