### ISSUE TITLE
Configure Log Level for CLI

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#383]
### Summary of the Feature
It should be possible to configure the log level in the command line interface. This is needed so that customers can run in DEBUG mode to provide us with detailed information of their problem.

### Acceptance Criteria
- [ ] A configuration parameter allows to run a higher log leven than INFO, if is ok, to only allow to switch on DEBUG level instead of offering the whole range of different log levels.
- [ ] If run with this parameter, logging information on the specified level is reported by the tool,. e.g. DEBUG information if log level is set to debug

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by sschuberth** [comment]
FYI, for Log4j 2 the log level can be set at runtime via [Configurator.setRootLevel()](https://github.com/heremaps/oss-review-toolkit/blob/0bcabe6850c0d6ee3cf3be07a6d1e13fe8d534e6/cli/src/main/kotlin/OrtMain.kt#L127-L130).

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-02-20
