### ISSUE TITLE
Maven module depends on maven frontend stubs

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#399]
### Summary of the Improvement
`maven-module` depends on the `maven-frontend-stubs`. 
This brings a lot of transitive dependencies (such as the problematic spdx -> jsonld-java combination). 
It is desirable to not have this dependency.

### Acceptance Criteria
- [x] `maven-module` does not depend on `maven-frontend-stubs`

### Definition of Done
- Acceptance criteria fulfilled
- The ticket describes what has been done and describes how the results can be verified (e.g. new Jenkins step is inserted, the report can be viewed at X)
- All known limitations are listed and it is described how they will be addressed (e.g., a ticket for the remaining stuff)
- Documentation is updated
- The result has been reviewed: Everything works as described and can be verified reading only the documentation

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-01-23
