### ISSUE TITLE
 Compliance Tool: Implement Component Approval with SW360

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#410]
### Summary of the Feature

Implement Component Approval in this way:
- Compliance Tool either gathers a compliance report as SPDX file (e.g. from Fossology) or creates a simple text file with the necessary compliance information (license situation, copyrights)
- Compliance Tool uploads this file to SW360 as Clearing Report Attachment
- Compliance Tool sets the attachment as accepted
- SW360 automatically sets the Clearing State to Approved.´

### Acceptance Criteria
- [x] csv reader reads and writes said clearing document into csv-file
- [x] SW360 Release item contains an accepted Clearing Report Attachment
- [x] SW360 Release item clearing state is Approved
- [x] Current Artifact Clearing State is a way to represent source of approval / way of approval

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-02-20
