### ISSUE TITLE
Compliance Tool: Documentation

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#415]
### Summary of the Improvement
Compliance Tool needs a more extended documentation, describing how it works and what it does *exactly* 

### Acceptance Criteria
- [x] Documentation is written
- [x] contains information about getting started / how to use
- [x] contains information about how it works

### Definition of Done
- Acceptance criteria fulfilled
- The ticket describes what has been done and describes how the results can be verified (e.g. new Jenkins step is inserted, the report can be viewed at X)
- All known limitations are listed and it is described how they will be addressed (e.g., a ticket for the remaining stuff)
- Documentation is updated
- The result has been reviewed: Everything works as described and can be verified reading only the documentation

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-03-05
