### ISSUE TITLE
ORT result analyzer should be able to upload source artifacts as attachments to SW360

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#424]
### Summary of the Feature
During an ORT scan run, ORT downloads the sources and generates a zip file containg the sources and it generates a scancode result file. These files should be reused by the ORT result analyzer to generate corresponding ArtifactFacts, so that the files can be uploaded to SW360 as attachments.

### Acceptance Criteria
- [ ] ORT result analyzer generates an ArtifactFact for the downloaded sources.zip
- [ ] ORT result analyzer generates an ArtifactFact for the scancode result file as clearing report
- [ ] Check that all findings of the ORT scan run are added (observed license and copyrights)

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by sschuberth** [comment]
Closing this because, if at all, this should be implemented as a follow-up to https://github.com/oss-review-toolkit/ort/pull/3235 directly in ORT.
