### ISSUE TITLE
Provide a container that supports the ORT/Antenna compliance toolchain with necessary configuration possibilities

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#425]
### Summary of the Improvement
A common container that contains the ORT/Antenna toolchain as a commonly usable Dockerfile. It should be easy to configure to add e.g., SW360 credentials or a branded template for document generation.

### Acceptance Criteria
- [ ] A Dockerfile exists that combines the whole toolchain with the needed configuration possibilities
- [ ] An example Jenkinsfile that allows to execute the container in a Jenkins environment
- [ ] Potentially support for other build environments (Azure, Travis, GH actions)
- [ ] A versioning concept for the combination of Antenna and ORT

### Definition of Done
- Acceptance criteria fulfilled
- The ticket describes what has been done and describes how the results can be verified (e.g. new Jenkins step is inserted, the report can be viewed at X)
- All known limitations are listed and it is described how they will be addressed (e.g., a ticket for the remaining stuff)
- Documentation is updated
- The result has been reviewed: Everything works as described and can be verified reading only the documentation

**Comment by sschuberth** [comment]
Superseded by ORT's [Dockerfile](https://github.com/oss-review-toolkit/ort/blob/master/Dockerfile) / [Jenkinsfile](https://github.com/oss-review-toolkit/ort/blob/master/Jenkinsfile).
