### ISSUE TITLE
Provide a Container for a csv file based approach to work with SW360 for component clearing

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#427]
### Summary of the Feature
Provide a container setup that runs with a csv file that lists the used components and then process the normal antenna workflow with configuration possibilities needed for e.g. the attribution document generation and the SW360 access information.

### Acceptance Criteria
- [ ] A Dockerfile exists that builds a container which runs a csv based antenna config
- [ ] Configuration possibilities as expected as given
- [ ] Build runs protypically on OSMI Jenkins, or if available on the existing OSMI  internal and external infrastructure

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by sschuberth** [comment]
The CSV-file-based approach will be superseded by a YAML-file-base one, or a UI in SW360.
