### ISSUE TITLE
Incorrect kotlin compile configuration and failing test case in ort module

### ISSUE THREAD

**Issue by oheger-bosch** [eclipse/antenna#428]
### Summary of the Bug
When executing the test case OrtResultAnalyzerTest.testParseOrtDataWithScanResultsToArtifacts() directly in the IDE it fails with an assertion in line 101. However, a `mvn clean install` on the project runs successfully and does not show any test failure.

The reason for this discrepancy is an incorrect build configuration in the pom of the ort module. Here the standard test source folder is set to /src/test/kotlin, while the test class (it is written in Java) is actually contained in /src/test/java. This directory structure is not compiled, and hence the test is not executed during a Maven build.

The test is actually wrong; it expects an incorrect VCS URL.

### Steps to reproduce
- Execute the test class OrtResultAnalyzerTest in the IDE. It will fail.

### Acceptance Criteria
- [x] The build configuration in the pom of the ort module is fixed, so that all unit tests in this module are executed during a build.
- [x] All unit tests in this module run successfully.

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by blaumeiser-at-bosch** [comment]
Review 2020-02-20
