### ISSUE TITLE
Export CycloneDX format

### ISSUE THREAD

**Issue by robertklaus-bosch** [eclipse/antenna#461]
### Summary of the Feature
Antenna could provide the option to export the collected information as Bill-of-Material (BOM) in  [CycloneDX](https://cyclonedx.org/) format.
The idea is to provide a generator ax extension that uses the internal information and creates a bom.xml as result.
This file can then be used for further processing, e.g. by uploading it to [OWASP Dependency-Track](https://owasp.org/www-project-dependency-track/). Users doing this can use Antenna for compliance and with the same information get information on security vulnerabilities.
As Antenna can be combined with different scan tools and it allows the possibility to enrich the data on artifacts, it can prove to create a rich BOM for users making it a lot more attractive.

### Acceptance Criteria
- [x] A module/extension for Antenna exists that can be added via standard configuration 
- [x] A bom.xml file is created, that is valid cyclonedx specification  
- [x] bom.xml is attached to Maven build (when using Maven)
- [x] A documentation of the usage/configuration exists

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by robertklaus-bosch** [comment]
"A bom.xml file is created," .. more specific it is created as output of the tool. Was not precise enough.

**Comment by robertklaus-bosch** [comment]
@blaumeiser-at-bosch I think this is complete now. Do I close this or does the reviewer?

**Comment by blaumeiser-at-bosch** [comment]
Pull request merged, close this
