### ISSUE TITLE
SW360 204 No_Content Responses are processed as a succesfull request and causes Exception

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#480]
### Summary of the Bug
[A SW360 commit](https://github.com/eclipse/sw360/commit/bd996419b959fd57a17080290323f1d86529316c#diff-fc8bf46fc1e710f969b71bcd6141aacf) introduced a `204 NO_CONTENT` response to some request, causing Antenna to wrongly process it as successful since it only checks if the response is 200...300, as is usual for the [okhttp3.isSuccessfull check](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-response/is-successful/) 

### Steps to reproduce
- Run antenna with a SW360 instance with no projects.

### Acceptance Criteria
- [ ] Response needs to be properly checked and reacted to
- [ ] No Exception is caused
- [ ] All changed request responses of above mentioned commit are checked and changed 

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by neubs-bsi** [comment]
> <@U6L2MTT71> Unfortunately the latest master of Antenna still has the same/similar issues. When running against SW360 8.0.1, SW360 returns a response with status code 204 (NO_CONTENT) with a null body. Antenna tries to process this body and throws an exception. What it should be doing is recognising a null body as “no projects match that name” and trying to create a project instead.
```<https://sw360.verifa.io/resource/api/projects?name=SpringBootExampleProject>
get_projects_by_name
HttpUtils:checkResponse(...): response.statusCode(): 204
HttpUtils:checkResponse(...): response.body().available(): 0
[ERROR] Failed HTTP request GET <https://sw360.verifa.io/resource/api/projects?name=SpringBootExampleProject>
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (okio.RealBufferedSource$inputStream$1); line: 1, column: 0]
    at com.fasterxml.jackson.databind.exc.MismatchedInputException.from (MismatchedInputException.java:59)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading (ObjectMapper.java:4360)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose (ObjectMapper.java:4205)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue (ObjectMapper.java:3251)
    at org.eclipse.sw360.antenna.http.utils.HttpUtils.lambda$jsonResult$2 (HttpUtils.java:225)
    at org.eclipse.sw360.antenna.http.utils.HttpUtils.lambda$checkResponse$0 (HttpUtils.java:148)
    at org.eclipse.sw360.antenna.http.HttpClientImpl$1.onResponse (HttpClientImpl.java:87)```
Output by the following changes:
```ublic CompletableFuture&lt;List&lt;SW360Project&gt;&gt; searchByName(String name) {
        String queryUrl = HttpUtils.addQueryParameter(resourceUrl(PROJECTS_ENDPOINT),
                SW360Attributes.PROJECT_SEARCH_BY_NAME, name);
        System.out.println(queryUrl);
        System.out.println(TAG_GET_BY_NAME);
        return executeJsonRequest(HttpUtils.get(queryUrl), SW360ProjectList.class, TAG_GET_BY_NAME)
                .thenApply(SW360ResourceUtils::getSw360Projects);
    }```
And:
```public static &lt;T&gt; ResponseProcessor&lt;T&gt; checkResponse(ResponseProcessor&lt;T&gt; processor,
                                                         Predicate&lt;Response&gt; successPredicate,
                                                         String tag) {
        
        return response -&gt; {
            System.out.println("HttpUtils:checkResponse(...): response.statusCode(): " + response.statusCode());
            System.out.println("HttpUtils:checkResponse(...): response.body().available(): " + response.bodyStream().available());
            if (!successPredicate.test(response)) {
                throw new FailedRequestException(tag, response.statusCode());
            }
            return processor.process(response);
        };
    }```

<sub>[View in Slack](https://sw360chat.slack.com/archives/CPEQGCLVA/p1585641878008900)</sub>

**Comment by oheger-bosch** [comment]
Responses with status code 204 and no response entity are now handled correctly by the SW360 client library.
