### ISSUE TITLE
SW360: Components must be assigned a category

### ISSUE THREAD

**Issue by oheger-bosch** [eclipse/antenna#489]
### Summary of the Bug
The SW360 project has changed the validation rules for resources of type _component_. Before a component is created or an existing one is updated, it is checked whether the component has a name and at least one category. So far, the SW360 client library does not support categories for components. This has the effect that no components can be created.

### Steps to reproduce
This is hard to reproduce directly as the problem is in a low-level library. One option could be using the compliance tool. Creations and updates of components should fail.

### Acceptance Criteria
- [ ] SW360Component is extended by a field for categories, which is a set of strings.
- [ ] Categories are taken into account in requests and responses when interacting with the SW360 server.
- [ ] Before Antenna attempts to create or update a component in SW360, it has to be ensured that a category is set.

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by neubs-bsi** [comment]
Note: we don't update components in Antenna. The only thing we do is to create them when they don't exist with the most basic fields
