### ISSUE TITLE
Extract common logic for Antenna CLI frontends related to logging and parameter parsing

### ISSUE THREAD

**Issue by oheger-bosch** [eclipse/antenna#505]
### Summary of the Improvement
The Antenna CLI now supports command line options to enable debug logging. This functionality is useful for other CLIs as well, e.g. for the compliance tool. So it makes sense to extract it to some base classes in the _cli-frontend-stub_ module.

### Acceptance Criteria
- [ ] Logic to enable debug logging and parsing the related command line options is available in reusable form in the cli-frontend-stub project.
- [ ] The concrete frontends make use of this functionality.
- [ ] Code duplication related to this feature is reduced.

### Definition of Done
- Acceptance criteria fulfilled
- The ticket describes what has been done and describes how the results can be verified (e.g. new Jenkins step is inserted, the report can be viewed at X)
- All known limitations are listed and it is described how they will be addressed (e.g., a ticket for the remaining stuff)
- Documentation is updated
- The result has been reviewed: Everything works as described and can be verified reading only the documentation

**Comment by neubs-bsi** [comment]
This has been done already, hasn't it? @oheger-bosch 

The logic exists for the compliance tool and the CLI. Gradle and Maven have their own individual handlings, I believe.

**Comment by oheger-bosch** [comment]
Yes, I think, this can be closed.
