### ISSUE TITLE
Support of additional metadata for Open Source Management

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#508]
### Summary of the Feature
For proper handling of Open Source Metadata, the following information needs to be stored and exchanged with SW360:

- Is the component modified internally or used as published by the OSS project
- In the concrete project, how is the component linked (this is a project property and not a component property)

### Acceptance Criteria
- [ ] The information is stored in the antenna model
- [ ] The storage of the information in SW360 is defined
- [ ] The exchange with SW360 is adapted to store and retrieve the data
- [ ] The CSV analyzer understands the concepts and enters them into the model

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by sschuberth** [comment]
FYI, ORT's Package(Ref) data model already captures the [linkage](https://github.com/oss-review-toolkit/ort/blob/e4b6019cb1bec25992478bcdc9d673673ca8264e/model/src/main/kotlin/PackageReference.kt#L48-L54) and thus Antenna's [OrtResultAnalyzer](https://github.com/eclipse/antenna/blob/master/modules/ort/src/main/kotlin/workflow/analyzers/OrtResultAnalyzer.kt) could simply pass on this information. For capturing a "modified" state I've just filed https://github.com/oss-review-toolkit/ort/issues/2922.

**Comment by sschuberth** [comment]
Closing this in favor of the above mentioned issues in conjunction with https://github.com/oss-review-toolkit/ort/issues/3024.
