### ISSUE TITLE
Reporting of additional obligations

### ISSUE THREAD

**Issue by blaumeiser-at-bosch** [eclipse/antenna#509]
### Summary of the Feature
Antenna has to identify additional obligations for identified licenses, which cannot be handled by the automation. The obligations need to be reported at the end of the workflow

### Acceptance Criteria
- [ ] License knowledgebases provide information on obligations, it is defined how and clarified with compliance experts
- [ ] Not automated obligations are identified and gathered for the project
- [ ] For now, the text report of Antenna should list the gathered obligations

### Definition of Done
- Acceptance criteria fulfilled
- A PR is created, the CI infrastructure reports green
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Test cases are created to prove the functionality of the feature
- Documentation is updated

**Comment by sschuberth** [comment]
It was brought up during the discussion that license identification should stay separate from the resulting license obligations, and the reporting thereof. For the latter, there is no component in Antenna yet, but in ORT there is (analyzer / scanner vs. evaluator). Thus, our decision was to not do this in the Antenna project but rely on ORT's existing functionality here.
