### ISSUE TITLE
Table of Contents

### ISSUE THREAD

**Issue by durikr** [eclipse/antenna#569]
### Summary of the Feature
For a better overview over the disclosure document an additional "Table of Contents" page that comes after the copyright page could be added.

### Acceptance Criteria
- [ ] Table of Contents is implemented
- [ ] Every chapter is shown in the Table of Contents (1. Acknowledgements, 2. Third Party Licenses and Components, ...)

### Definition of Done
- Acceptance criteria fulfilled

**Comment by sschuberth** [comment]
My understanding is that you came here as a user of [ORT](https://github.com/oss-review-toolkit/ort)'s [AntennaAttributionDocumentReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AntennaAttributionDocumentReporter.md). Thus, my recommendation would be to use the new [AsciidocTemplateReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AsciidocTemplateReporter.md) instead, which can be customized to your needs via a self-made Asciidoc-template.
