### ISSUE TITLE
Add Policy Engine to Antenna

### ISSUE THREAD

**Issue by Martin-Idel-SI** [eclipse/antenna#57]
Add a policy engine to antenna: Allow to define rules in the project or externally which will be validated against all artifacts.

PRs connected to this effort:
- #43 add initial drools engine
- #46 Build policy testing harness to allow simple rule validation
- #49 more tests for rules spanning multiple artifacts
- #50 read policy evaluations from file

Future: 
- Use BDD to validate rules (cucumber)
- Allow configuration of many folders to draw rules.

**Comment by blaumeiser-at-bosch** [comment]
@Martin-Idel-SI : Can this be closed

**Comment by Martin-Idel-SI** [comment]
@blaumeiser-at-bosch Once #122 is merged, I think it should.
Before, the implementation is not really usable as it's undocumented.
