### ISSUE TITLE
Include Chapter "Acknowledgements"

### ISSUE THREAD

**Issue by durikr** [eclipse/antenna#570]
### Summary of the Improvement
A chapter (page) named "Acknowledgements" should be added after the Table of Contents with the Text:

_"The **NAME OF PROJECT** utilizes third-party software components. This disclosure document lists these software components and their licenses."_

### Acceptance Criteria
- [ ] Page with "Acknowledgements" is added
- [ ] Text with placeholder where project title should be added is created

### Definition of Done
- Acceptance criteria fulfilled

**Comment by sschuberth** [comment]
My understanding is that you came here as a user of [ORT](https://github.com/oss-review-toolkit/ort)'s [AntennaAttributionDocumentReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AntennaAttributionDocumentReporter.md). Thus, my recommendation would be to use the new [AsciidocTemplateReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AsciidocTemplateReporter.md) instead, which can be customized to your needs via a self-made Asciidoc-template.
