### ISSUE TITLE
Different Headers

### ISSUE THREAD

**Issue by durikr** [eclipse/antenna#571]
### Summary of the Improvement
For each chapter there should be a different header with the name of the chapter. (exception: Cover page and Copyright page should have no header)

### Acceptance Criteria
- [ ] Each Chapter has it's own header (e.g. Chapter 1. Acknowledgements, Chapter 2. Third Party Licenses and Components, etc...)

### Definition of Done
- Acceptance criteria fulfilled

**Comment by sschuberth** [comment]
My understanding is that you came here as a user of [ORT](https://github.com/oss-review-toolkit/ort)'s [AntennaAttributionDocumentReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AntennaAttributionDocumentReporter.md). Thus, my recommendation would be to use the new [AsciidocTemplateReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AsciidocTemplateReporter.md) instead, which can be customized to your needs via a self-made Asciidoc-template.
