### ISSUE TITLE
License Text as Appendixes

### ISSUE THREAD

**Issue by durikr** [eclipse/antenna#572]
### Summary of the Improvement
License Texts are shown after all the dependecies are listed. Each License should be shown as an Appendix. For example: **"Appendix A. Apache License 2.0"**

### Acceptance Criteria
- [ ] Each License should be shown as an Appendix 
- [ ] Every Appendix also should have it's own header which contains the name of the title (e.g. Appendix A. Apache License 2.0)

### Definition of Done
- Acceptance criteria fulfilled

**Comment by sschuberth** [comment]
My understanding is that you came here as a user of [ORT](https://github.com/oss-review-toolkit/ort)'s [AntennaAttributionDocumentReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AntennaAttributionDocumentReporter.md). Thus, my recommendation would be to use the new [AsciidocTemplateReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AsciidocTemplateReporter.md) instead, which can be customized to your needs via a self-made Asciidoc-template.
