### ISSUE TITLE
Roman/Arabic numerals

### ISSUE THREAD

**Issue by durikr** [eclipse/antenna#573]
### Summary of the Improvement
Before the third-party disclosure document actually begins, the numerals should be Roman. (e.g. I, II, III, IV, ...). Exception: Cover page should not show any numerals. Table of Contents should be the last page with Roman numerals. After that the pagination should start with Arabic numerals starting from 1 and showing how many pages the document has with a slash. (e.g. 1/34)

### Acceptance Criteria
- [ ] Roman numerals until "Table of Contents"
- [ ] Arabic numerals after "Table of Contents"
- [ ] Cover page shouldn't show any numerals

### Definition of Done
- Acceptance criteria fulfilled

**Comment by sschuberth** [comment]
My understanding is that you came here as a user of [ORT](https://github.com/oss-review-toolkit/ort)'s [AntennaAttributionDocumentReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AntennaAttributionDocumentReporter.md). Thus, my recommendation would be to use the new [AsciidocTemplateReporter](https://github.com/oss-review-toolkit/ort/blob/master/docs/reporters/AsciidocTemplateReporter.md) instead, which can be customized to your needs via a self-made Asciidoc-template.
