### ISSUE TITLE
Compliance Tool: When clearing state is set to approved ECC in SW360 gets approved

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/antenna#576]
### Summary of the Bug

When using the compliance tool updater to clear artifacts / releases via SW360 not only does the clearing state get set to "Approved" but also the ECC checks. This two checks are not the same, since one is concerned with license checking and the other with reuse.  

### Steps to reproduce
- Clear any release via the compliance tool updater with the status OSM_APPROVED
- check the release on your corresponding instance and see that both clearing state and ECC checks are approved

### Acceptance Criteria
- [ ] reason for that is explored
- [ ] follow up issues or handling strategies are documented

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by KorSin** [comment]
It seems that this not directly related to the OSM_APPROVED status of a release but rather an (presumably) intended feature of SW360. If the release is tagged as OSS and also has a valid URL, the ECC status in SW360 is automatically set to APPROVED; see [here](https://github.com/eclipse/sw360/blob/886a1e3bda6b7f6c5a0fed07334d132c59e7c103/backend/src-common/src/main/java/org/eclipse/sw360/datahandler/db/ComponentDatabaseHandler.java#L887-L892). The intention is (probably but not verified) that if open source code is openly available in the web, it might not be under ECC control. Nevertheless, this fact should be documented in the documentation of the compliance tool.
