### ISSUE TITLE
Documentation: still contains "SW360 Project Coordinates"

### ISSUE THREAD

**Issue by RalphBallhorn** [eclipse/antenna#602]
### Summary of the Bug
As per #444 SW360ProjectCoordinates are said to have been removed from config.xml. Unfortunately Antenna documentation of config.xml still refers to "SW360 Project Coordinates" at two locations.

### Steps to reproduce
- read https://eclipse.github.io/antenna/SNAPSHOT/config-configuration.html#

### Acceptance Criteria
- [ ] full text search over the entire documentation shall neither find term "SW360 Project Coordinates" nor "SW360ProjectCoordinates"

### Definition of Done
- Documentation is updated
- Acceptance criteria fulfilled

**Comment by neubs-bsi** [comment]
Hello Ralph,
thank you for finding and filing this bug. 
I have created a pull request to fix this oversight. 
Feel free to check it out. 

Kind regards,
Steph
