### ISSUE TITLE
Antenna ignores user defined project version; instead it falls back to version 1.0 always

### ISSUE THREAD

**Issue by RalphBallhorn** [eclipse/antenna#612]
### Summary of the Bug
Hello,  
testing current snapshot (2020-10-19) using CLI I detected that Antenna ignores user defined project version, even though everything is configured as per the documentation\.  
Please refer to first bullet in paragraph "Steps to reproduce"\. In SW360 a new project Antenna_Version_Test \(9\.9\.9\.9\) should have been created, but it really is Antenna_Version_Test \(1\.0\)\.  
  
Even though I'm new to Antenna I'd like to suggest below change\. As per my tests with SW360 it solves the issue and furthermore it doesn't break any of the existing automated tests\. Still, I'm uncertain whether there are better ways to achieve the same\. 
  
change line 166 in  
core\\frontend-stubs\\cli-frontend-stub\\src\\main\\java\\org\\eclipse\\sw360\\antenna\\frontend\\stub\\cli\\AntennaCLISettingsReader\.java  
from  
readAntennaStringSetting\(reader, "version", "1\.0", toolConfigBuilder::setVersion\);  
to
readAntennaStringSetting\(reader, "version", reader\.getStringProperty\("version"\), toolConfigBuilder::setVersion\);  
  
Kind Regards  
Ralph  

### Steps to reproduce
- create a toolConfiguration.xml that contains
\<plugin\>
	\<configuration\>
		\<productFullname\>Antenna_Version_Test\</productFullname\>
		\<version\>9\.9\.9\.9\</version\>
	\</configuration\>
\</plugin\>
- run Antenna to update SW360
- check version number in SW360

### Acceptance Criteria
- [ ] create a test with project version defined to 9.9.9.9
- [ ] with above configuration in SW360 a new project Antenna_Version_Test \(9\.9\.9\.9\) is being created

### Definition of Done
- Acceptance criteria fulfilled
- A test case is created to reproduce the bug
- A PR is created, the CI infrastructure reports green, the bug test case proves that bug is fixed
- The PR is reviewed and approved
- No TODOs left in the code unless explained in the ticket, if something else is still open, this is summarized in a comment in the issue
- Documentation is updated

**Comment by RalphBallhorn** [comment]
Regarding Definition of Done   
The documentation is not affected by the suggested change\.

**Comment by neubs-bsi** [comment]
Hello @RalphBallhorn,
if you want you could do this as a pull request, since you are already aware of were changes should be applied. We are more than happy to review it and assist with any questions regarding a contribution. 

Kind regards,
Steph
